apiVersion: apps/v1
kind: Deployment
metadata:
  name: quota-management-server
  labels:
    app: quota-management-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quota-management-server
  template:
    metadata:
      labels:
        app: quota-management-server
    spec:
      containers:
      - name: server
        image: docker.io/vladpbr/quota-management-server:1.0
        ports:
        - containerPort: 5000
        env:
        - name: QUOTA_SCHEME_FILE
          value: "/app/scheme.json"
        - name: MANAGED_NAMESPACE_LABEL
          value: "managed_quota=true"
        volumeMounts:
        - name: scheme
          mountPath: "/app/scheme.json"
          subPath: "scheme.json"
          readOnly: true
        imagePullPolicy: Always
      volumes:
      - name: scheme
        configMap:
          name: quota-scheme
