apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: quota-management
  annotations:
    description: "OpenShift application for easy management of resources for projects located within the deployed cluster."
objects:
- apiVersion: oauth.openshift.io/v1
  grantMethod: auto
  kind: OAuthClient
  metadata:
    name: ${CLIENT_ID}
  redirectURIs:
  - https://quota-management.${ROUTER_CANONICAL_HOSTNAME}
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: quota-scheme
  data:
    scheme.json: |
      {
          "compute": {
              "pods": {
                  "name": "Pods",
                  "description": "The total number of pods in a non-terminal state that can exist in the project.",
                  "units": "",
                  "regex": "^\\d+$"
              },
              "requests.cpu": {
                  "name": "CPU Cores",
                  "description": "The sum of CPU requests across all pods in a non-terminal state cannot exceed this value.",
                  "units": "",
                  "regex": "^\\d*\\.?\\d*$"
              },
              "requests.memory": {
                  "name": "Memory",
                  "description": "The sum of memory requests across all pods in a non-terminal state cannot exceed this value.",
                  "units": "Gi",
                  "regex": "^\\d*\\.?\\d*$"
              }
          },
          "storage": {
              "requests.storage": {
                  "name": "Storage",
                  "description": "The sum of storage requests across all persistent volume claims in any state cannot exceed this value.",
                  "units": "Gi",
                  "regex": "^\\d*\\.?\\d*$"
              },
              "persistentvolumeclaims": {
                  "name": "Persistent Volume Claims",
                  "description": "The total number of persistent volume claims that can exist in the project.",
                  "units": "",
                  "regex": "^\\d+$"
              }
          }
      }
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quota-management-client
    labels:
      app: quota-management-client
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: quota-management-client
    template:
      metadata:
        labels:
          app: quota-management-client
      spec:
        containers:
        - name: server
          image: ${CLIENT_IMAGE}
          ports:
          - containerPort: 3200
          resources:
            requests:
              memory: "64Mi"
              cpu: ".1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3200
          env:
          - name: BACKEND_ROUTE
            value: "https://quota-management-server.${ROUTER_CANONICAL_HOSTNAME}"
          - name: OAUTH_ENDPOINT
            value: "https://oauth-openshift.${ROUTER_CANONICAL_HOSTNAME}"
          - name: OAUTH_CLIENT_ID
            value: "${CLIENT_ID}"
          imagePullPolicy: Always
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quota-management-server
    labels:
      app: quota-management-server
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: quota-management-server
    template:
      metadata:
        labels:
          app: quota-management-server
      spec:
        containers:
        - name: server
          image: ${SERVER_IMAGE}
          ports:
          - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: ".1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
          env:
          - name: QUOTA_SCHEME_FILE
            value: "/app/scheme.json"
          - name: MANAGED_NAMESPACE_LABEL
            value: "${MANAGED_NAMESPACE_LABEL}"
          volumeMounts:
          - name: scheme
            mountPath: "/app/scheme.json"
            subPath: "scheme.json"
            readOnly: true
          imagePullPolicy: Always
        volumes:
        - name: scheme
          configMap:
            name: quota-scheme
- apiVersion: v1
  kind: Service
  metadata:
    name: quota-management-client
  spec:
    selector:
      app: quota-management-client
    ports:
      - protocol: TCP
        port: 3200
        targetPort: 3200
- apiVersion: v1
  kind: Service
  metadata:
    name: quota-management-server
  spec:
    selector:
      app: quota-management-server
    ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: quota-management-client
  spec:
    host: quota-management.${ROUTER_CANONICAL_HOSTNAME}
    to:
      kind: Service
      name: quota-management-client
      weight: 100
    port:
      targetPort: 3200
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: quota-management-server
  spec:
    host: quota-management-server.${ROUTER_CANONICAL_HOSTNAME}
    to:
      kind: Service
      name: quota-management-server
      weight: 100
    port:
      targetPort: 5000
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
parameters:
- description: Client ID for the UI to use
  value: quota-management
  name: CLIENT_ID
  required: true
- description: Label which should be applied to managed namespaces
  value: managed-quota=true
  name: MANAGED_NAMESPACE_LABEL
  required: true
- description: Router's wildcard DNS record
  name: ROUTER_CANONICAL_HOSTNAME
  required: true
- description: Docker image to use for the UI
  value: docker.io/vladpbr/quota-management-client:1.0
  name: CLIENT_IMAGE
  required: true
- description: Docker image to use for the backend
  value: docker.io/vladpbr/quota-management-server:1.0
  name: SERVER_IMAGE
  required: true