apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: quota-management
  annotations:
    description: "OpenShift application for easy management of resources for projects located within the deployed cluster."
objects:
- apiVersion: oauth.openshift.io/v1
  grantMethod: auto
  kind: OAuthClient
  metadata:
    name: ${CLIENT_ID}
  redirectURIs:
  - https://quota-management.${ROUTER_CANONICAL_HOSTNAME}
- apiVersion: user.openshift.io/v1
  kind: Group
  metadata:
    name: ${QUOTA_MANAGERS_GROUP}
  users: []
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: quota-scheme
    namespace: ${NAMESPACE}
  data:
    scheme.json: |
      {
          "compute": {
              "pods": {
                  "name": "Pods",
                  "units": "",
                  "regex": "^\\d+$",
                  "regex_description": "Must be a whole non-negative number"
              },
              "requests.cpu": {
                  "name": "CPU Cores",
                  "units": "",
                  "regex": "^\\d*\\.?\\d*$",
                  "regex_description": "Must be a floating point non-negative number"
              },
              "requests.memory": {
                  "name": "Memory",
                  "units": "Gi",
                  "regex": "^\\d*\\.?\\d*$",
                  "regex_description": "Must be a floating point non-negative number"
              }
          },
          "storage": {
              "requests.storage": {
                  "name": "Storage",
                  "units": "Gi",
                  "regex": "^\\d*\\.?\\d*$",
                  "regex_description": "Must be a floating point non-negative number"
              },
              "persistentvolumeclaims": {
                  "name": "Persistent Volume Claims",
                  "units": "",
                  "regex": "^\\d+$",
                  "regex_description": "Must be a whole non-negative number"
              }
          }
      }
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: quota-manager
    namespace: ${NAMESPACE}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: quota-manager
  rules:
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - namespaces
    verbs:
    - list
  - apiGroups:
    - ""
    resources:
    - resourcequotas
    verbs:
    - update
  - apiGroups:
    - user.openshift.io
    resources:
    - groups
    resourceNames:
    - ${QUOTA_MANAGERS_GROUP}
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: quota-manager
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: quota-manager
  subjects:
  - kind: ServiceAccount
    name: quota-manager
    namespace: ${NAMESPACE}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quota-management-client
    namespace: ${NAMESPACE}
    labels:
      app: quota-management-client
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: quota-management-client
    template:
      metadata:
        labels:
          app: quota-management-client
      spec:
        containers:
        - name: server
          image: ${CLIENT_IMAGE}
          ports:
          - containerPort: 3200
          resources:
            requests:
              memory: "64Mi"
              cpu: ".1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3200
          env:
          - name: BACKEND_ROUTE
            value: "https://quota-management-server.${ROUTER_CANONICAL_HOSTNAME}"
          - name: OAUTH_ENDPOINT
            value: "https://${OAUTH_ENDPOINT}"
          - name: OAUTH_CLIENT_ID
            value: "${CLIENT_ID}"
          imagePullPolicy: Always
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: quota-management-server
    namespace: ${NAMESPACE}
    labels:
      app: quota-management-server
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: quota-management-server
    template:
      metadata:
        labels:
          app: quota-management-server
      spec:
        serviceAccountName: quota-manager
        containers:
        - name: server
          image: ${SERVER_IMAGE}
          ports:
          - containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: ".1"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
          env:
          - name: QUOTA_SCHEME_FILE
            value: "/app/scheme.json"
          - name: MANAGED_NAMESPACE_LABEL
            value: "${MANAGED_NAMESPACE_LABEL}"
          - name: QUOTA_MANAGERS_GROUP
            value: "${QUOTA_MANAGERS_GROUP}"
          volumeMounts:
          - name: scheme
            mountPath: "/app/scheme.json"
            subPath: "scheme.json"
            readOnly: true
          imagePullPolicy: Always
        volumes:
        - name: scheme
          configMap:
            name: quota-scheme
        - name: users
          configMap:
            name: quota-management-users
- apiVersion: v1
  kind: Service
  metadata:
    name: quota-management-client
    namespace: ${NAMESPACE}
  spec:
    selector:
      app: quota-management-client
    ports:
      - protocol: TCP
        port: 3200
        targetPort: 3200
- apiVersion: v1
  kind: Service
  metadata:
    name: quota-management-server
    namespace: ${NAMESPACE}
  spec:
    selector:
      app: quota-management-server
    ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: quota-management-client
    namespace: ${NAMESPACE}
  spec:
    host: quota-management.${ROUTER_CANONICAL_HOSTNAME}
    to:
      kind: Service
      name: quota-management-client
      weight: 100
    port:
      targetPort: 3200
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
- kind: Route
  apiVersion: route.openshift.io/v1
  metadata:
    name: quota-management-server
    namespace: ${NAMESPACE}
  spec:
    host: quota-management-server.${ROUTER_CANONICAL_HOSTNAME}
    to:
      kind: Service
      name: quota-management-server
      weight: 100
    port:
      targetPort: 5000
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
parameters:
- description: Namespace in which to deploy the quota management
  name: NAMESPACE
  required: true
- description: Client ID for the UI to use
  value: quota-management
  name: CLIENT_ID
  required: true
- description: Name for the quota managers group
  value: quota-managers
  name: QUOTA_MANAGERS_GROUP
  required: true
- description: Endpoint to use for authentication
  name: OAUTH_ENDPOINT
  required: true
- description: Label which should be applied to managed namespaces
  value: managed-quota=true
  name: MANAGED_NAMESPACE_LABEL
  required: true
- description: Router's wildcard DNS record
  name: ROUTER_CANONICAL_HOSTNAME
  required: true
- description: Docker image to use for the UI
  value: docker.io/vladpbr/quota-management-client:1.0
  name: CLIENT_IMAGE
  required: true
- description: Docker image to use for the backend
  value: docker.io/vladpbr/quota-management-server:1.0
  name: SERVER_IMAGE
  required: true