apiVersion: v1
kind: ServiceAccount
metadata:
  name: quota-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: quota-manager
rules:
- apiGroups:
  - ""
  resources:
  - resourcequotas
  - namespaces
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - project.openshift.io
  resources:
  - projectrequests
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quota-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quota-manager
subjects:
- kind: ServiceAccount
  name: quota-manager
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: quota-manager-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: quota-manager
  namespace: default